(function(){
var f=navigator.userAgent.toLowerCase();google.isOpera=f.indexOf("opera")!=-1;google.isIE=document.all&&f.indexOf("msie")!=-1&&!google.isOpera;google.isSafari=f.indexOf("safari")!=-1;google.time=function(){return(new Date).getTime()};google.log=function(a,c){(new Image).src="/gen_204?atyp=i&ct="+a+"&cad="+c+"&zx="+google.time()};google.xhr=function(){var a=null;if(window.XMLHttpRequest)try{a=new XMLHttpRequest}catch(c){}else if(window.ActiveXObject)for(var d=0,b;b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0",
"MSXML2.XMLHTTP","Microsoft.XMLHTTP"][d++];)try{a=new ActiveXObject(b);break}catch(c){}return a};function g(a,c,d){var b=document.defaultView&&document.defaultView.getComputedStyle(a,""),e=b&&b.getPropertyValue(c);return document.defaultView&&b&&typeof e=="string"&&(d?e:parseInt(e,10))}google.getHeight=function(a){return g(a,"height")||a.offsetHeight};google.getWidth=function(a){return g(a,"width")||a.offsetWidth};google.getColor=function(a){return a.currentStyle?a.currentStyle.color:g(a,"color",
1)};google.rhs=function(){};window.google.bind=function(a,c,d){var b="on"+c;if(a.addEventListener)a.addEventListener(c,d,false);else if(a.attachEvent)a.attachEvent(b,d);else{var e=a[b];a[b]=function(){var h=e.apply(this,arguments),i=d.apply(this,arguments);return h==undefined?i:(i==undefined?h:i&&h)}}};
})();
(function(){
var a=document.getElementById("tads"),b=document.getElementById("3po");google.rhs=function(){if(!google.drhs)if(document.getElementById("mbEnd")&&(a||b)){var d=google.getHeight(document.getElementById("rhsline")),c=a?google.getHeight(a):0;if(b)c+=google.getHeight(b)+18;document.getElementById("rhspad").style.height=c>d?Math.min(9999,c-d)+"px":(google.isIE?"":0)}};google.rhs();google.bind(window,"resize",google.rhs);
})();
(function(){
var c,e,h,j="",l=null,o=null,p=null,q=-1,s,t,u,v,w,x,z,A=0,B=0,C=null,D=0;var F;var I=null,J=0;
var L=0,aa=new RegExp("^[\\s\\u1100-\\u11FF\\u3040-\\u30FF\\u3130-\\u318F\\u31F0-\\u31FF\\u3400-\\u4DBF\\u4E00-\\u9FFF\\uAC00-\\uD7A3\\uF900-\\uFAFF\\uFF65-\\uFFDC]+$");function ba(a,b,d,f,g){s=a;t=b;z=["/complete/search","?hl=",google.kHL,"&gl=cn",(d?"&ds="+d:""),(f?"&pq="+encodeURIComponent(f):"")].join("");google.bind(s,"submit",M);t.setAttribute("autocomplete","off");google.bind(t,"blur",function(){if(!L)N();L=0});google.bind(t,"keydown",O);google.bind(t,"keyup",P);
e=(h=(c=t.value));F=Q(t);u=document.createElement("table");u.cellSpacing=(u.cellPadding="0");v=u.style;u.className="gac_m";s.appendChild(u);N();R();google.bind(window,"resize",R);window.setInterval(function(){var m=t.value;if(m!=c)S(0);c=m},10);w=T("aq","f");x=T("oq",e);var k=document.createElement("style");document.getElementsByTagName("head")[0].appendChild(k);var i=null;i=k.sheet;
var n=function(m,Y){var Z=m+" { "+Y+" }";i.insertRule(Z,i.cssRules.length);};
n(".gac_m","font-size:13px;cursor:default;line-height:17px;border:1px solid black;z-index:99;background:white;position:absolute;margin:0;");n(".gac_b","background:#36c;color:white;");var y="white-space:nowrap;overflow:hidden;text-align:left;padding-left:3px;";n(".gac_c",y);n(".gac_d","white-space:nowrap;overflow:hidden;text-align:right;font-size:10px;color:green;padding:0 3px");
n(".gac_b td","color:white");n(".gac_e td","padding:0 3px 2px;text-align:right;font-size:10px;line-height:15px");n(".gac_e span","color:#00c;text-decoration:underline;cursor:pointer");U();}function R(){if(u){v.left=V(t,"offsetLeft")+"px";v.top=V(t,"offsetTop")+t.offsetHeight-1+"px";v.width=t.offsetWidth+"px";}}function T(a,b){var d=document.createElement("input");d.type="hidden";d.name=a;d.value=b;return s.appendChild(d)}function O(a){var b=a.keyCode;if(b==27&&ca()){N();W(e);a.cancelBubble=true;return a.returnValue=false}if(b==38||b==40){B++;if(B%3==1)S(b);return false}}function P(a){var b=a.keyCode;if(B==0&&!(b==38||b==40))S(b);B=0;}function S(a){if(a==38||a==40){L=1;t.blur();window.setTimeout(function(){t.focus()},10)}if(t.value!=c){e=t.value;F=Q(t);x.value=e}a==40&&da(q+1);a==38&&da(q-1);R();if(j!=e&&!C)C=window.setTimeout(N,500);c=t.value;if(c==""&&!l)U()}function ea(){if(D)return;if(p)p.className="gac_a";this.className="gac_b";p=this;for(var a=0,b;b=o[a];a++)b==
p&&(q=a)}function da(a){if(!j&&e){h="";U();return}if(e!=j||!l)return;if(!o||o.length<=0)return;if(!ca()){X();return}var b=o.length-1;if(p)p.className="gac_a";if(a==b||a==-1){q=-1;W(e);t.focus();w.value="f";return}else if(a>b)a=0;else if(a<-1)a=b-1;q=a;p=o.item(a);p.className="gac_b";W(p.completeString);w.value=p.completeId}function N(){if(C){window.clearTimeout(C);C=null}v.visibility="hidden";}function X(){v.visibility="visible";R();D=1}function ca(){return v.visibility=="visible"}function fa(a){A>0&&A--;if(a[0]!=e)return;if(C){window.clearTimeout(C);C=null}j=a[0];u.innerHTML="";
var d=0;for(var f=0,g;f<a[1].length;f++)if(g=a[1][f]){d++;var k=u.insertRow(-1);k.onclick=function(){W(this.completeString);M();
s.submit();};k.onmousedown=ga;k.onmouseover=ea;k.onmousemove=function(){if(D){D=0;ea.call(this)}};k.completeString=g[0];k.completeId=g[2];k.className="gac_a";var i=document.createElement("td");$(i,g[0]);i.className="gac_c";
k.appendChild(i);var r=document.createElement("td");$(r,g[1]);r.className="gac_d";k.appendChild(r);}if(d>0){var n=u.insertRow(-1);n.onmousedown=ga;var y=document.createElement("td");y.colSpan=2;n.className="gac_e";var m=document.createElement("span");n.appendChild(y);y.appendChild(m);
$(m,"¹Ø±Õ");m.onclick=function(){N();j="";window.clearTimeout(l);l=null;w.value="x"}}q=-1;o=u.rows;(o.length>0?X:N)()}function M(){N();if(x.value!=t.value)w.value=o.item(q).completeId;else{x.value="";if(A>=10||J>=3)w.value="o"}}function U(){if(J>=3)return;if(h!=
e&&e){A++;ha(encodeURIComponent(e));t.focus()}h=e;var f=100;for(var g=1;g<=(A-2)/
2;++g)f*=2;f+=50;l=window.setTimeout(U,f)}function W(a){t.value=a;c=a}function V(a,b){var d=0;while(a){d+=a[b];a=a.offsetParent}return d}function $(a,b){a.appendChild(document.createTextNode(b))}function ga(a){
return false}function ia(){var a=null;if(typeof XMLHttpRequest!="undefined")a=new XMLHttpRequest;return a}function ha(a){if(I&&I.readyState!=0&&I.readyState!=4)I.abort();if(I)I.onreadystatechange=function(){};I=ia();if(I){I.open("GET",
z+"&xhr=t&q="+a+"&cp="+F,true);I.onreadystatechange=function(){if(I.readyState==4)switch(I.status){case 403:J=1000;break;case 302:case 500:case 502:case 503:J++;break;case 200:fa(eval(I.responseText));default:J=0}};I.send(null)}}function Q(a){var b=0,d=0;if(ja(a)){b=a.selectionStart;d=a.selectionEnd}return b&&d&&b==d?b:0}function ja(a){try{return typeof a.selectionStart=="number"}catch(b){return false}}window.google.ac={i:ba,h:fa};
})();
if(!window.gbar||!gbar.close){;};
(function (){
var a="google";if(window[a]){window[a].a={};window[a].b=1;window[a].report=function(h,g,i){var d="";{if(window[a].pt){d+="&srt="+window[a].pt;delete window[a].pt}try{d+="&tran="+window.external.tran}catch(n){}}{var j=document.getElementById("csi");if(j.value)return;j.value=1}var b=h.t,e=b.start;delete b.start;var k=[];for(var f in b)e&&k.push(f+"."+(b[f]>e?b[f]-e:e-b[f]));if(g)for(var l in g)d+="&"+l+"="+g[l];var c=new Image,m=window[a].b++;window[a].a[m]=c;c.onload=(c.onerror=function(){delete window[a].a[m]});
c.src=[i?i:"/csi","?v=3","&s="+(window[a].sn?window[a].sn:"GWS")+"&action=",h.name,d,"&rt=",k.join(",")].join("");c=null}};if(google.timers&&google.timers.load.t){google.timers.load.t.xjs=(new Date).getTime();google.timers.load.t.ol&&google.report(google.timers.load,{ei:google.kEI,e:google.kEXPI})};
})();
if(google.y.first){for(var a=0,b;b=google.y.first[a];++a)b();delete google.y.first}for(a in google.y)google.y[a][1]?google.y[a][1].apply(google.y[a][0]):google.y[a][0].go();google.x=function(d,c){c&&c.apply(d);return false};
